name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q

